### ISSUE TITLE
Can't Extract text from PDF

### ISSUE THREAD

**Issue by raaffaaeell** [BMKEG/lapdftextProject#1]
Hello there, I was trying to use this tool to extract text. I tried with some PDFs and I get this error

encountered invalid value for space in RTSpatialRepresentation.getMostPopularVerticalSpaceBetweenWordsPage

It's not a easy pdf.

Also, in another ones it extracts only a portion of the text.

I don't know if I can attach them here, but if you really need I can email you them.

Cheers

**Comment by ghost** [comment]
Dear Rafael, 

The tool tries to pull out information about the average text spatial distribution for PDFs to help it build blocks that it can then classify. The error that you found constitutes a bug, so could you mail me the PDF at gully@usc.edu?

Thanks

Gul
