### ISSUE TITLE
mvn clean package command from the README fails

### ISSUE THREAD

**Issue by dragoon** [BMKEG/lapdftextProject#2]
Exception

```
org.xml.sax.SAXParseException; /Users/dragoon/Projects/lapdftextProject/src/main/xsd/XSD-Blue/journalpublishing3.xsd (No such file or directory)
```

Probably some paths are configured incorrectly, but I cannot identify where.

**Comment by ghost** [comment]
Ok. Should be fixed now.

We are discontinuing the use of XSLT files for extracting text from the *.nxml format for open access documents and instead using the Python script nxml2txt (https://github.com/spyysalo/nxml2txt) as implmented through our UimaBioc library (https://github.com/BMKEG/UimaBioC). 

This will also require the use of BioC annotations as the standard data processing element in our Uima work and that will take a little time to get into the current version of LAPDF text...

**Comment by dragoon** [comment]
Thanks, it works!
